spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true  #convenience for docker image
  datasource:
    username: sa
    password:
    #url: jdbc:h2:~/test
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1

# Spring 1.5 has secured actuators by default.
management:
  security:
    enabled: false
  info:
    git:
      mode: full
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
